### ISSUE TITLE
examples/basic/hello: panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by mewmew** [lakal3/VGE#7]
```
$ env LD_LIBRARY_PATH=. ./hello
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/lakal3/vge/vge/dldyn.Invoke.func3(0x7f634c572a00, 0x1b6aa30, 0xc00009a770, 0x28)
	/home/u/Desktop/VGE/vge/dldyn/dl.go:95 +0xa5
github.com/lakal3/vge/vge/dldyn.Invoke(0x7f634c572a00, 0x2, 0x1b6aa30, 0xc00009a770, 0x0, 0x28)
	/home/u/Desktop/VGE/vge/dldyn/dl.go:95 +0xfb
github.com/lakal3/vge/vge/vk.call_NewDesktop(0x577148, 0x6b0de0, 0x1b6aa30, 0xc00009a770)
	/home/u/Desktop/VGE/vge/vk/libcall_linux_amd64.go:796 +0xaa
github.com/lakal3/vge/vge/vk.NewDesktop(0x577148, 0x6b0de0, 0xc0000ce000, 0x6f676f6c)
	/home/u/Desktop/VGE/vge/vk/desktop.go:22 +0xa5
github.com/lakal3/vge/vge/vapp.Desktop.InitApp()
	/home/u/Desktop/VGE/vge/vapp/win.go:117 +0xed
github.com/lakal3/vge/vge/vapp.Init(0x54ab00, 0x4, 0xc0000b3f58, 0x2, 0x2)
	/home/u/Desktop/VGE/vge/vapp/app.go:71 +0x218
main.main()
	/home/u/Desktop/VGE/examples/basic/hello.go:20 +0xcc
```

From https://golang.org/pkg/cmd/cgo/#hdr-C_references_to_Go

> Go code may pass a Go pointer to C provided the Go memory to which it points does not contain any Go pointers.

**Comment by mewmew** [comment]
Note to self: while debugging this issue `GODEBUG=cgocheck=0` may be used to disable these checks. Still the original error would have to be fixed, as otherwise C code may reference a pointer that Go GC has potentially moved (?).

**Comment by lakal3** [comment]
VGE will assume that Go will not move objects in use. VGE library is aware of Go runtime and will never use any memory after call from VGE C++ library returns. This implementation violates Go’s  CGO rules but speeds up interface a lot as we do not have to copy potentially large entities like images several times.

If Go will someday implement moving garbage collector VGE library will stop working. I still assume that moving collector is not very likely due to Go inner pointers and other Go specific stuff.

However, if Go switches to moving collector then VGE must allocate all memory from C++ module. We should be able to handle this in interface generation and should not require manual changes to code.

**Comment by lakal3** [comment]
Maybe interface generator should have an optional switch to generate CGO safe call in Linux. In Windows, this check is not required at least for now. GCO check will not effect DLL calls in Windows

**Comment by lakal3** [comment]
GODEBUG settings has now a better documentation in readme.md and architecture.md
